from pathlib import Path

def rep(path,old,new):
 p=Path(path);s=p.read_text();assert old in s,(path,old[:50]);p.write_text(s.replace(old,new,1))
rep('app/models.py','class OrderAdjustment(Base):\n','''class ProductShippingSetting(Base):\n    __tablename__="product_shipping_settings"\n    product_id:Mapped[str]=mapped_column(ForeignKey("products.id",ondelete="CASCADE"),primary_key=True)\n    shipping_type:Mapped[str]=mapped_column(String(20),default="DEFAULT")\n    shipping_fee:Mapped[int]=mapped_column(Integer,default=0)\n    updated_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now,onupdate=now)\n\nclass OrderAdjustment(Base):\n''')
rep('app/main.py','from .models import User, AuthSession, Product, ProductNaverSetting, DesignSetting, Order, OrderItem, Shipment, Inquiry, BoardPost, Category, ProductOption, OrderAdjustment, Coupon, UserCoupon, PointLedger','from .models import User, AuthSession, Product, ProductNaverSetting, DesignSetting, Order, OrderItem, Shipment, Inquiry, BoardPost, Category, ProductOption, ProductShippingSetting, OrderAdjustment, Coupon, UserCoupon, PointLedger')
rep('app/main.py','version="11.0"','version="12.0"')
rep('app/main.py','return {"ok":True,"version":"11.0"}','return {"ok":True,"version":"12.0"}')
rep('app/main.py','''    options=[]\n    if db is not None:\n        rows=db.scalars(select(ProductOption).where(ProductOption.product_id==p.id).order_by(ProductOption.sort_order,ProductOption.created_at)).all()\n        options=[{"id":o.id,"name":o.name,"price":o.price,"active":o.is_active,"sortOrder":o.sort_order} for o in rows]\n''','''    options=[]; shipping_type="DEFAULT"; shipping_fee=0\n    if db is not None:\n        rows=db.scalars(select(ProductOption).where(ProductOption.product_id==p.id).order_by(ProductOption.sort_order,ProductOption.created_at)).all()\n        options=[{"id":o.id,"name":o.name,"price":o.price,"active":o.is_active,"sortOrder":o.sort_order} for o in rows]\n        ss=db.get(ProductShippingSetting,p.id)\n        if ss: shipping_type=ss.shipping_type or "DEFAULT"; shipping_fee=max(0,int(ss.shipping_fee or 0))\n''')
rep('app/main.py','"detailTitle":p.detail_title,"detailText":p.detail_text,"detailImages":detail_images,"options":options}','"detailTitle":p.detail_title,"detailText":p.detail_text,"detailImages":detail_images,"options":options,"shippingType":shipping_type,"shippingFee":shipping_fee}')
rep('app/main.py','''            if a: adj={"subtotal":a.subtotal,"shippingFee":a.shipping_fee,"couponDiscount":a.coupon_discount,"pointDiscount":a.point_discount,"couponId":a.coupon_id,"couponName":a.coupon_name}\n    except: adj=None\n''','''            if a: adj={"subtotal":a.subtotal,"shippingFee":a.shipping_fee,"couponDiscount":a.coupon_discount,"pointDiscount":a.point_discount,"couponId":a.coupon_id,"couponName":a.coupon_name}\n            reward=int(_db.scalar(select(func.coalesce(func.sum(PointLedger.amount),0)).where(PointLedger.order_id==o.id,PointLedger.amount>0,PointLedger.reason.like("구매 적립%"))) or 0)\n    except: adj=None; reward=0\n''')
rep('app/main.py','"paymentMethod":o.payment_method,"paymentStatus":o.payment_status,"orderStatus":o.order_status,','"paymentMethod":o.payment_method,"paymentStatus":o.payment_status,"orderStatus":o.order_status,"rewardPoints":reward,"rewardRate":reward_rate_percent(o.payment_method),')
rep('app/main.py','    options:list[ProductOptionIn]=[]\n','    options:list[ProductOptionIn]=[]\n    shippingType:str="DEFAULT"\n    shippingFee:int=Field(default=0,ge=0,le=1000000)\n')
rep('app/main.py','''@app.post("/api/orders")\ndef create_order(data:OrderIn,request:Request,db:Session=Depends(get_db)):\n''','''REWARD_BPS={"CARD":50,"NAVERPAY":50,"KAKAOPAY":50,"CASH":150}\ndef reward_rate_percent(m:str):return REWARD_BPS.get(m,0)/100.0\ndef order_reward_base(db,o):\n a=db.get(OrderAdjustment,o.id);return max(0,int(o.total_amount or 0)-int(a.shipping_fee if a else 0))\ndef award_order_points(db,o):\n if not o or (o.user_id or "").startswith("guest_") or o.payment_status!="PAID":return 0\n b=REWARD_BPS.get(o.payment_method,0);e=int(db.scalar(select(func.coalesce(func.sum(PointLedger.amount),0)).where(PointLedger.order_id==o.id,PointLedger.amount>0,PointLedger.reason.like("구매 적립%"))) or 0)\n if not b or e:return e\n pts=order_reward_base(db,o)*b//10000\n if pts:db.add(PointLedger(id=new_id("pt"),user_id=o.user_id,amount=pts,reason=f"구매 적립 {o.order_no} ({reward_rate_percent(o.payment_method):g}%)",order_id=o.id))\n return pts\ndef product_shipping(db,pid):\n r=db.get(ProductShippingSetting,pid)\n if not r:return "DEFAULT",0\n k=(r.shipping_type or "DEFAULT").upper();return (k if k in {"DEFAULT","FREE","FIXED"} else "DEFAULT",max(0,int(r.shipping_fee or 0)))\ndef calculate_shipping(db,items,subtotal,commerce):\n fixed=0;default=False;seen=set()\n for p,*_ in items:\n  if p.id in seen:continue\n  seen.add(p.id);k,f=product_shipping(db,p.id)\n  if k=="FIXED":fixed+=f\n  elif k=="DEFAULT":default=True\n base=int(commerce.get("shippingFee",0) or 0) if default and subtotal<int(commerce.get("freeShippingThreshold",0) or 0) else 0\n return max(0,fixed+base)\n\n@app.post("/api/orders")\ndef create_order(data:OrderIn,request:Request,db:Session=Depends(get_db)):\n''')
rep('app/main.py','shipping=0 if subtotal>=int(commerce.get("freeShippingThreshold",0) or 0) else int(commerce.get("shippingFee",0) or 0)','shipping=calculate_shipping(db,items,subtotal,commerce)')
rep('app/main.py','if u: point_balance=int(db.scalar(select(func.coalesce(func.sum(PointLedger.amount),0)).where(PointLedger.user_id==u.id)) or 0)','if u: point_balance=max(0,int(db.scalar(select(func.coalesce(func.sum(PointLedger.amount),0)).where(PointLedger.user_id==u.id)) or 0))')
rep('app/main.py','o.payment_status="PAID";o.order_status="PAID"\n    elif status=="WAITING_FOR_DEPOSIT":','o.payment_status="PAID";o.order_status="PAID";award_order_points(db,o)\n    elif status=="WAITING_FOR_DEPOSIT":')
rep('app/main.py','o.payment_status="PAID";o.order_status="PAID"\n    elif status in {"CANCELED","ABORTED","EXPIRED"}:','o.payment_status="PAID";o.order_status="PAID";award_order_points(db,o)\n    elif status in {"CANCELED","ABORTED","EXPIRED"}:')
rep('app/main.py','phone="",role="admin",is_active=True,payment_customer_key=new_id("cus")))\n        db.commit()','phone="",role="admin",is_active=True,payment_customer_key=new_id("cus")))\n        elif os.getenv("RESET_ADMIN_PASSWORD","false").lower()=="true":\n            admin.password_hash=hash_password(pwd)\n        db.commit()')
